from typing import Protocol, runtime_checkable, Callable, Optional


@runtime_checkable
class IMenuIcon(Protocol):
    icon_label: str
    icon_path: object
    icon_text: str
    callback: Optional[Callable]


@runtime_checkable
class IFolderWidget(Protocol):
    ID: int
    folder_name: str
    buttons: list
    translate_fn: Optional[Callable]

    def add_app(self, app_name: str, icon_path, callback=None) -> None: ...
    def set_grayed_out(self, grayed_out: bool) -> None: ...
    def update_title_label(self, message=None) -> None: ...
    def update_folder_preview(self) -> None: ...


@runtime_checkable
class IExpandedView(Protocol):
    def add_app_icon(self, widget, row: int, col: int) -> None: ...
    def fade_in(self, center_pos) -> None: ...
    def fade_out(self) -> None: ...
    def show_close_app_button(self) -> None: ...
    def hide_close_app_button(self) -> None: ...


@runtime_checkable
class IOverlay(Protocol):
    def fade_in(self) -> None: ...
    def fade_out(self) -> None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def resize(self, *args) -> None: ...


@runtime_checkable
class IFloatingIcon(Protocol):
    def show_with_animation(self) -> None: ...
    def hide_with_animation(self) -> None: ...
    def move(self, x: int, y: int) -> None: ...


@runtime_checkable
class IExpandedViewManager(Protocol):
    def show_expanded_view(self, folder_name, overlay_parent, on_close, on_app_selected, on_minimize, on_close_app): ...
    def populate_apps(self, buttons: list) -> None: ...
    def fade_in(self, center_pos) -> None: ...
    def fade_out(self) -> None: ...
    def show_close_button(self) -> None: ...
    def hide_close_button(self) -> None: ...


@runtime_checkable
class IFloatingIconManager(Protocol):
    def show_floating_icon(self, folder_name: str, on_click_callback: Callable) -> None: ...
    def hide_floating_icon(self) -> None: ...


@runtime_checkable
class IOverlayManager(Protocol):
    def show_overlay(self): ...
    def hide_overlay(self) -> None: ...
    def set_style(self, style: str) -> None: ...


@runtime_checkable
class IAppWidget(Protocol):
    app_name: str

    def close_app(self) -> None: ...
    def on_language_changed(self) -> None: ...
    def clean_up(self) -> None: ...


@runtime_checkable
class UIFactory(Protocol):
    def create_folder_widget(self, ID: int, folder_name: str) -> IFolderWidget: ...
    def create_expanded_view_manager(self, folder_widget) -> IExpandedViewManager: ...
    def create_floating_icon_manager(self, folder_widget) -> IFloatingIconManager: ...
    def create_overlay_manager(self, folder_widget, overlay_parent, overlay_callback) -> IOverlayManager: ...
