from src.robot_systems.glue.domain.workpieces.repository.i_workpiece_repository import IWorkpieceRepository
from src.robot_systems.glue.domain.workpieces.repository.json_workpiece_repository import JsonWorkpieceRepository
