from abc import ABC, abstractmethod


class IGlueProcessDriverService(ABC):
    @abstractmethod
    def capture_and_match(self) -> dict: ...

    @abstractmethod
    def get_latest_matched_workpieces(self) -> list: ...

    @abstractmethod
    def get_latest_match_summary(self) -> dict: ...

    @abstractmethod
    def select_matched_workpieces(self, indexes: list[int]) -> None: ...

    @abstractmethod
    def build_job_from_latest_match(self): ...

    @abstractmethod
    def get_latest_job(self): ...

    @abstractmethod
    def get_latest_job_summary(self): ...

    @abstractmethod
    def load_latest_job(self, spray_on: bool) -> None: ...

    @abstractmethod
    def prepare_and_load(self, spray_on: bool): ...

    @abstractmethod
    def prepare_load_and_start(self, spray_on: bool): ...

    @abstractmethod
    def get_process_snapshot(self): ...

    @abstractmethod
    def set_manual_mode(self, enabled: bool) -> None: ...

    @abstractmethod
    def is_manual_mode_enabled(self) -> bool: ...

    @abstractmethod
    def step_once(self): ...

    @abstractmethod
    def start(self) -> None: ...

    @abstractmethod
    def pause(self) -> None: ...

    @abstractmethod
    def resume(self) -> None: ...

    @abstractmethod
    def stop(self) -> None: ...

    @abstractmethod
    def reset_errors(self) -> None: ...
