from __future__ import annotations

import logging
from dataclasses import dataclass, field
from time import perf_counter

import cv2
import numpy as np
from scipy.optimize import least_squares

from src.engine.robot.path_preparation.geometry import (
    PATH_TANGENT_HEADING_DEADBAND_DEG,
    PATH_TANGENT_LOOKAHEAD_DISTANCE_MM,
    rebuild_pose_path_from_xy,
)
from src.robot_systems.paint.processes.paint.plan.paint_contour_interpolation_debug import (
    save_paint_contour_interpolation_debug_plot,
    show_paint_contour_interpolation_debug_plot,
)

_logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PaintContourInterpolationConfig:
    """Paint contour processing settings.

    The processor is unit-agnostic. In production paint execution it receives
    robot-space millimetres after pixel-to-mm conversion; in standalone vision
    experiments it may receive pixels. No integer rounding is performed here.
    """

    units: str = "mm"
    fit_sample_spacing: float = 1.0
    output_spacing: float = 1.0
    corner_epsilon_ratio: float = 0.004
    bezier_max_error: float = 1.5
    bezier_min_points: int = 10
    bezier_max_depth: int = 10
    sharp_boundary_deg: float = 45.0
    tangent_lookahead_distance_mm: float = PATH_TANGENT_LOOKAHEAD_DISTANCE_MM
    tangent_heading_deadband_deg: float = PATH_TANGENT_HEADING_DEADBAND_DEG
    rz_mode: str = "path_tangent"


@dataclass(frozen=True)
class PaintContourInterpolationResult:
    """Path representations generated by the paint-only interpolation experiment."""

    units: str
    raw_path: list[list[float]]
    prepared_path: list[list[float]]
    heading_path: list[list[float]]
    execution_path: list[list[float]]
    anchor_xy: list[list[float]]
    cleaned_anchor_xy: list[list[float]] = field(default_factory=list)
    sharp_boundary_xy: list[list[float]] = field(default_factory=list)

    @property
    def raw_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.raw_path, dtype=float)[:, :2])

    @property
    def execution_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.execution_path, dtype=float)[:, :2])


class PaintContourInterpolation:
    """Curve-preserving paint contour processor.

    The algorithm mirrors the validated standalone runner:
    normalize float XY, sample the closed source contour uniformly, detect hard
    contour corners, fit adaptive cubic Beziers between corners, then sample the
    fitted curve back to a float XY contour. It removes local camera/jitter noise
    while preserving continuous curvature instead of collapsing arcs into chords.
    """

    def __init__(self, config: PaintContourInterpolationConfig | None = None) -> None:
        self._config = config or PaintContourInterpolationConfig()

    def build(self, robot_path: list[list[float]], *, include_debug_paths: bool = True) -> PaintContourInterpolationResult:
        total_start = perf_counter()
        raw_path = [list(point) for point in robot_path]
        if len(raw_path) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path,
                heading_path=raw_path,
                execution_path=raw_path,
                anchor_xy=[list(point[:2]) for point in raw_path],
            )

        stage_start = perf_counter()
        raw_xy = _clean_xy(np.asarray(raw_path, dtype=float)[:, :2])
        _log_interpolation_timing("clean_xy", stage_start, input_points=len(raw_path), output_points=len(raw_xy))
        if len(raw_xy) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path[:1],
                heading_path=raw_path[:1],
                execution_path=raw_path[:1],
                anchor_xy=[list(point[:2]) for point in raw_path[:1]],
            )

        stage_start = perf_counter()
        dense_xy = _resample_closed_xy(raw_xy, self._config.fit_sample_spacing)
        _log_interpolation_timing(
            "fit_resample_closed_xy",
            stage_start,
            input_points=len(raw_xy),
            output_points=len(dense_xy),
        )

        stage_start = perf_counter()
        smooth_stats: dict[str, float | int] = {}
        prepared_xy, corner_indices = _smooth_closed_xy_with_beziers(dense_xy, self._config, stats=smooth_stats)
        _log_interpolation_timing(
            "smooth_closed_xy_with_beziers",
            stage_start,
            input_points=len(dense_xy),
            output_points=len(prepared_xy),
            corners=len(corner_indices),
            bezier_fits=smooth_stats.get("fit_count", 0),
            least_squares_s=f"{float(smooth_stats.get('least_squares_s', 0.0)):.3f}",
            max_fit_error=f"{float(smooth_stats.get('max_error', 0.0)):.4f}",
        )
        cleaned_anchor_xy = dense_xy if include_debug_paths else np.empty((0, 2), dtype=float)

        stage_start = perf_counter()
        sharp_boundary_xy = _sharp_tangent_boundary_xy(
            prepared_xy,
            threshold_deg=self._config.sharp_boundary_deg,
        )
        _log_interpolation_timing(
            "sharp_tangent_boundary_xy",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(sharp_boundary_xy),
        )
        corner_xy = prepared_xy[np.asarray(corner_indices, dtype=int)] if corner_indices else np.empty((0, 2))
        preserve_xy = _merge_unique_xy_points(corner_xy, sharp_boundary_xy)

        stage_start = perf_counter()
        if include_debug_paths:
            prepared_path = rebuild_pose_path_from_xy(
                prepared_xy,
                raw_path,
                self._config.rz_mode,
                tangent_lookahead_distance_mm=self._config.tangent_lookahead_distance_mm,
                tangent_heading_deadband_deg=self._config.tangent_heading_deadband_deg,
                tangent_boundary_xy=sharp_boundary_xy,
            )
        else:
            prepared_path = _pose_path_from_xy(prepared_xy, raw_path)
        _log_interpolation_timing(
            "rebuild_prepared_pose_path",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(prepared_path),
            debug_paths=include_debug_paths,
        )

        stage_start = perf_counter()
        execution_xy = resample_contour_xy(
            prepared_xy,
            spacing=self._config.output_spacing,
            closed=True,
        )
        _log_interpolation_timing(
            "execution_resample_contour_xy",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(execution_xy),
        )

        stage_start = perf_counter()
        fair_stats: dict[str, float | int] = {}
        execution_xy = _fair_resampled_contour_xy(
            execution_xy,
            spacing=self._config.output_spacing,
            closed=True,
            stats=fair_stats,
        )
        _log_interpolation_timing(
            "fair_resampled_contour_xy",
            stage_start,
            output_points=len(execution_xy),
            passes=fair_stats.get("passes", 0),
            candidates=fair_stats.get("candidates", 0),
            removed=fair_stats.get("removed", 0),
            vector_eval_s=f"{float(fair_stats.get('vector_eval_s', 0.0)):.3f}",
        )

        stage_start = perf_counter()
        execution_path = rebuild_pose_path_from_xy(
            execution_xy,
            raw_path,
            self._config.rz_mode,
            tangent_lookahead_distance_mm=self._config.tangent_lookahead_distance_mm,
            tangent_heading_deadband_deg=self._config.tangent_heading_deadband_deg,
            tangent_boundary_xy=sharp_boundary_xy,
        )
        _log_interpolation_timing(
            "rebuild_execution_pose_path",
            stage_start,
            input_points=len(execution_xy),
            output_points=len(execution_path),
        )
        _log_interpolation_timing(
            "paint_contour_interpolation_total",
            total_start,
            input_points=len(raw_path),
            output_points=len(execution_path),
        )

        return PaintContourInterpolationResult(
            units=self._config.units,
            raw_path=raw_path,
            prepared_path=prepared_path,
            heading_path=prepared_path if include_debug_paths else [],
            execution_path=execution_path,
            anchor_xy=preserve_xy.tolist(),
            cleaned_anchor_xy=cleaned_anchor_xy.tolist(),
            sharp_boundary_xy=sharp_boundary_xy.tolist() if include_debug_paths else [],
        )


def _log_interpolation_timing(label: str, started_at: float, **fields: object) -> None:
    suffix = " ".join(f"{key}={value}" for key, value in fields.items())
    if suffix:
        suffix = " " + suffix
    _logger.info("[PATH_PREP_TIMING] stage=%s elapsed_s=%.3f%s", label, perf_counter() - started_at, suffix)


def resample_contour_xy(
    xy_points: np.ndarray,
    *,
    spacing: float,
    closed: bool = True,
) -> np.ndarray:
    """Return a float XY contour/path sampled at approximately *spacing* units.

    This is a linear arclength resampler only. It does not smooth, simplify, or
    fit curves. Use it after pixel-to-mm conversion when the contour shape has
    already been finalized and only execution density is needed.
    """
    source_xy = _remove_degenerate_backtracks(np.asarray(xy_points, dtype=float))
    if closed:
        cleaned = _remove_short_chord_kinks(
            _remove_degenerate_backtracks(_resample_closed_xy(source_xy, spacing)),
            min_chord=max(0.05, float(spacing) * 0.80),
            closed=True,
        )
        if _max_segment_length(cleaned) > float(spacing) * 1.01:
            cleaned = _resample_closed_xy(cleaned, spacing)
        return _close_if_needed(cleaned, True)

    cleaned = _remove_short_chord_kinks(
        _remove_degenerate_backtracks(_resample_open_xy(source_xy, spacing)),
        min_chord=max(0.05, float(spacing) * 0.80),
        closed=False,
    )
    if _max_segment_length(cleaned) > float(spacing) * 1.01:
        cleaned = _resample_open_xy(cleaned, spacing)
    return cleaned


def compute_min_rect_metrics(xy_points: np.ndarray) -> dict[str, float]:
    """Return OpenCV min-area rectangle metrics for XY points."""
    import cv2

    points = np.asarray(xy_points, dtype=np.float32)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return {
            "cx_mm": 0.0,
            "cy_mm": 0.0,
            "width_mm": 0.0,
            "height_mm": 0.0,
            "angle_deg": 0.0,
            "area_mm2": 0.0,
        }

    rect = cv2.minAreaRect(points[:, :2].reshape(-1, 1, 2))
    (cx, cy), (width, height), angle = rect
    width = float(width)
    height = float(height)
    angle = float(angle)
    if width < height:
        width, height = height, width
        angle += 90.0
    return {
        "cx_mm": float(cx),
        "cy_mm": float(cy),
        "width_mm": width,
        "height_mm": height,
        "angle_deg": angle,
        "area_mm2": width * height,
    }


def _resample_closed_xy(xy_points: np.ndarray, spacing: float) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return points

    closed_points = points
    if float(np.linalg.norm(points[0] - points[-1])) > 1e-9:
        closed_points = np.vstack([points, points[:1]])

    segment_lengths = np.linalg.norm(np.diff(closed_points, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    keep = np.r_[True, np.diff(cumulative) > 1e-9]
    closed_points = closed_points[keep]
    cumulative = cumulative[keep]
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return closed_points[:-1]

    spacing = max(0.05, float(spacing))
    sample_distances = np.arange(0.0, total_length, spacing)
    if len(sample_distances) < 3:
        sample_distances = np.linspace(0.0, total_length, 3, endpoint=False)
    return np.column_stack(
        [np.interp(sample_distances, cumulative, closed_points[:, dim]) for dim in range(2)]
    ).astype(np.float64)


def _resample_open_xy(xy_points: np.ndarray, spacing: float) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return points

    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    keep = np.r_[True, np.diff(cumulative) > 1e-9]
    points = points[keep]
    cumulative = cumulative[keep]
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return points

    spacing = max(0.05, float(spacing))
    sample_distances = list(np.arange(0.0, total_length, spacing))
    if not sample_distances or abs(sample_distances[-1] - total_length) > 1e-9:
        sample_distances.append(total_length)
    return np.column_stack(
        [np.interp(sample_distances, cumulative, points[:, dim]) for dim in range(2)]
    ).astype(np.float64)


def _max_segment_length(xy_points: np.ndarray) -> float:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return 0.0
    return float(np.max(np.linalg.norm(np.diff(points, axis=0), axis=1)))


def _pose_path_from_xy(xy_points: np.ndarray, reference_path: list[list[float]]) -> list[list[float]]:
    points = np.asarray(xy_points, dtype=float).reshape(-1, 2)
    reference = list(reference_path[0]) if reference_path else [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    while len(reference) < 6:
        reference.append(0.0)
    return [
        [
            float(point[0]),
            float(point[1]),
            float(reference[2]),
            float(reference[3]),
            float(reference[4]),
            float(reference[5]),
        ]
        for point in points
    ]


def _smooth_closed_xy_with_beziers(
    dense_xy: np.ndarray,
    config: PaintContourInterpolationConfig,
    *,
    stats: dict[str, float | int] | None = None,
) -> tuple[np.ndarray, list[int]]:
    dense = _clean_xy(dense_xy)
    if len(dense) < 3:
        return dense.astype(np.float64), []

    corner_indices = _find_corner_indices(dense, config.corner_epsilon_ratio)
    if len(corner_indices) < 3:
        return dense.astype(np.float64), []

    segments = _split_closed_points(dense, corner_indices)
    all_points: list[np.ndarray] = []
    for segment in segments:
        beziers = _adaptive_bezier_fit(segment, config, depth=0, stats=stats)
        for control_points in beziers:
            sampled = _sample_bezier_segment(control_points, config.output_spacing)
            if len(sampled):
                all_points.append(sampled[:-1] if len(sampled) > 1 else sampled)

    if not all_points:
        return dense.astype(np.float64), corner_indices
    result = _rotate_xy_to_nearest_start(_clean_xy(np.vstack(all_points)), dense[0])
    remapped_corner_indices = _nearest_indices(result, dense[np.asarray(corner_indices, dtype=int)])
    return result.astype(np.float64), remapped_corner_indices


def _rotate_xy_to_nearest_start(points: np.ndarray, start_xy: np.ndarray) -> np.ndarray:
    path = _clean_xy(points)
    if len(path) < 2:
        return path
    start = np.asarray(start_xy, dtype=np.float64).reshape(2)
    index = int(np.argmin(np.linalg.norm(path - start, axis=1)))
    if index <= 0:
        return path
    return np.vstack([path[index:], path[:index]])


def _nearest_indices(points: np.ndarray, query_points: np.ndarray) -> list[int]:
    path = _clean_xy(points)
    queries = _clean_xy(query_points)
    if len(path) == 0 or len(queries) == 0:
        return []
    indices = [int(np.argmin(np.linalg.norm(path - query, axis=1))) for query in queries]
    return sorted(set(indices))


def _find_corner_indices(dense_xy: np.ndarray, epsilon_ratio: float) -> list[int]:
    points = _clean_xy(dense_xy)
    if len(points) < 3:
        return []
    contour = np.ascontiguousarray(points.astype(np.float32).reshape(-1, 1, 2))
    epsilon = max(1e-6, float(epsilon_ratio)) * float(cv2.arcLength(contour, True))
    approx = cv2.approxPolyDP(contour, epsilon, True)
    corners = np.asarray(approx, dtype=np.float64).reshape(-1, 2)
    indices: list[int] = []
    for corner in corners:
        index = int(np.argmin(np.linalg.norm(points - corner, axis=1)))
        indices.append(index)
    return sorted(set(indices))


def _split_closed_points(points: np.ndarray, corner_indices: list[int]) -> list[np.ndarray]:
    dense = _clean_xy(points)
    count = len(dense)
    if count < 4:
        return []
    corners = sorted(set(int(index) % count for index in corner_indices))
    segments: list[np.ndarray] = []
    for start, end in zip(corners, corners[1:] + [corners[0] + count]):
        if end >= count:
            segment = np.vstack([dense[start:], dense[: end - count + 1]])
        else:
            segment = dense[start: end + 1]
        if len(segment) >= 4:
            segments.append(segment)
    return segments


def _bezier(t: np.ndarray, p0: np.ndarray, p1: np.ndarray, p2: np.ndarray, p3: np.ndarray) -> np.ndarray:
    parameter = np.asarray(t, dtype=np.float64)[:, None]
    return (
        (1.0 - parameter) ** 3 * p0
        + 3.0 * (1.0 - parameter) ** 2 * parameter * p1
        + 3.0 * (1.0 - parameter) * parameter ** 2 * p2
        + parameter ** 3 * p3
    )


def _fit_cubic_bezier(
    points: np.ndarray,
    *,
    stats: dict[str, float | int] | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
    samples = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    p0 = samples[0]
    p3 = samples[-1]
    chord = p3 - p0
    p1_initial = p0 + chord / 3.0
    p2_initial = p0 + 2.0 * chord / 3.0

    segment_lengths = np.linalg.norm(np.diff(samples, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return p0, p1_initial, p2_initial, p3, 0.0

    parameters = cumulative / total_length

    def residual(values: np.ndarray) -> np.ndarray:
        p1 = values[:2]
        p2 = values[2:]
        return (_bezier(parameters, p0, p1, p2, p3) - samples).ravel()

    started_at = perf_counter()
    result = least_squares(
        residual,
        np.hstack([p1_initial, p2_initial]),
        max_nfev=80,
    )
    if stats is not None:
        stats["fit_count"] = int(stats.get("fit_count", 0)) + 1
        stats["least_squares_s"] = float(stats.get("least_squares_s", 0.0)) + (perf_counter() - started_at)
    p1 = result.x[:2]
    p2 = result.x[2:]
    fitted = _bezier(parameters, p0, p1, p2, p3)
    error = float(np.max(np.linalg.norm(fitted - samples, axis=1)))
    if stats is not None:
        stats["max_error"] = max(float(stats.get("max_error", 0.0)), error)
    return p0, p1, p2, p3, error


def _adaptive_bezier_fit(
    points: np.ndarray,
    config: PaintContourInterpolationConfig,
    *,
    depth: int,
    stats: dict[str, float | int] | None = None,
) -> list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
    min_points = max(4, int(config.bezier_min_points))
    max_depth = max(1, int(config.bezier_max_depth))
    if len(points) < min_points or depth >= max_depth:
        p0, p1, p2, p3, _ = _fit_cubic_bezier(points, stats=stats)
        return [(p0, p1, p2, p3)]

    p0, p1, p2, p3, error = _fit_cubic_bezier(points, stats=stats)
    if error <= max(0.01, float(config.bezier_max_error)):
        return [(p0, p1, p2, p3)]

    midpoint = len(points) // 2
    return (
        _adaptive_bezier_fit(points[: midpoint + 1], config, depth=depth + 1, stats=stats)
        + _adaptive_bezier_fit(points[midpoint:], config, depth=depth + 1, stats=stats)
    )


def _sample_bezier_segment(
    control_points: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray],
    spacing: float,
) -> np.ndarray:
    p0, p1, p2, p3 = control_points
    approx_length = (
        float(np.linalg.norm(p1 - p0))
        + float(np.linalg.norm(p2 - p1))
        + float(np.linalg.norm(p3 - p2))
    )
    spacing = max(0.05, float(spacing))
    count = max(8, int(np.ceil(approx_length / spacing)) + 1)
    return _bezier(np.linspace(0.0, 1.0, count), p0, p1, p2, p3)


def _clean_xy(xy_points: np.ndarray) -> np.ndarray:
    points = np.asarray(xy_points, dtype=float)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return np.empty((0, 2), dtype=float)
    points = points[:, :2].copy()
    if len(points) < 2:
        return points
    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    keep_mask = np.concatenate([[True], segment_lengths > 1e-9])
    return points[keep_mask]


def _remove_degenerate_backtracks(xy_points: np.ndarray) -> np.ndarray:
    """Remove tiny reversed samples that create a local 180-degree fold."""
    points = _clean_xy(xy_points)
    if len(points) < 4:
        return points

    closed = float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 4:
        return _close_if_needed(points, closed)

    changed = True
    while changed and len(points) >= 4:
        changed = False
        keep = np.ones(len(points), dtype=bool)
        for index in range(len(points)):
            prev_index = (index - 1) % len(points) if closed else index - 1
            next_index = (index + 1) % len(points) if closed else index + 1
            if prev_index < 0 or next_index >= len(points):
                continue

            incoming = points[index] - points[prev_index]
            outgoing = points[next_index] - points[index]
            incoming_len = float(np.linalg.norm(incoming))
            outgoing_len = float(np.linalg.norm(outgoing))
            if incoming_len <= 1e-9 or outgoing_len <= 1e-9:
                continue
            if incoming_len > min(0.75, outgoing_len * 0.75):
                continue

            turn_cos = float(np.dot(incoming, outgoing) / (incoming_len * outgoing_len))
            if turn_cos > -0.95:
                continue

            bridge = points[next_index] - points[prev_index]
            bridge_len = float(np.linalg.norm(bridge))
            if bridge_len <= 1e-9:
                continue
            bridge_cos = float(np.dot(bridge, outgoing) / (bridge_len * outgoing_len))
            if bridge_cos < 0.95:
                continue

            keep[index] = False
            changed = True

        if changed:
            points = points[keep]

    return _close_if_needed(points, closed)


def _remove_short_chord_kinks(
    xy_points: np.ndarray,
    *,
    min_chord: float,
    closed: bool,
) -> np.ndarray:
    """Remove sub-spacing kink samples introduced by contour smoothing/resampling.

    The pivot projector treats every final contour segment as physical contact
    travel. A tiny chord with a large heading change becomes many near-pure
    rotation samples and can create a local cusp in the robot command path.
    """
    points = _clean_xy(xy_points)
    if len(points) < 4:
        return points

    if closed and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6:
        points = points[:-1]
    if len(points) < 4:
        return _close_if_needed(points, closed)

    min_chord = max(0.0, float(min_chord))
    changed = True
    while changed and len(points) >= 4:
        changed = False
        segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
        if closed:
            segment_lengths = np.append(
                segment_lengths,
                float(np.linalg.norm(points[0] - points[-1])),
            )

        short_segments = np.flatnonzero(segment_lengths < min_chord)
        if len(short_segments) == 0:
            break

        remove_candidates: list[int] = []
        for segment_index in short_segments:
            left_index = segment_index
            right_index = (segment_index + 1) % len(points)
            if not closed and (left_index == 0 or right_index == len(points) - 1):
                continue

            remove_left_score = _removal_turn_score(points, left_index, closed=closed)
            remove_right_score = _removal_turn_score(points, right_index, closed=closed)
            remove_index = left_index if remove_left_score <= remove_right_score else right_index
            if not closed and (remove_index <= 0 or remove_index >= len(points) - 1):
                continue
            remove_candidates.append(int(remove_index))

        if remove_candidates:
            selected_indices = _non_adjacent_indices(
                np.asarray(sorted(set(remove_candidates)), dtype=int),
                len(points),
                closed=closed,
            )
            if selected_indices:
                remove_mask = np.zeros(len(points), dtype=bool)
                remove_mask[np.asarray(selected_indices, dtype=int)] = True
                points = points[~remove_mask]
                changed = True

    return _close_if_needed(points, closed)


def _fair_resampled_contour_xy(
    xy_points: np.ndarray,
    *,
    spacing: float,
    closed: bool,
    stats: dict[str, float | int] | None = None,
) -> np.ndarray:
    """Remove tiny local resampling wiggles before pivot projection.

    Projection treats the source contour as physical contact geometry, so this
    pass is intentionally conservative: it only removes a point when the direct
    bridge stays within the paint-scale tolerance and clearly lowers local
    second-difference curvature.
    """
    points = _clean_xy(xy_points)
    if len(points) < 5:
        return points

    if closed and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6:
        points = points[:-1]
    if len(points) < 5:
        return _close_if_needed(points, closed)

    spacing = max(0.05, float(spacing))
    tolerance = max(0.03, min(0.10, spacing * 0.10))
    max_local_segment = spacing * 2.5
    max_bridge_segment = spacing * 3.0
    min_improvement_ratio = 0.35

    removed = 0
    max_bridge_error = 0.0
    passes = 0
    candidates_seen = 0
    vector_eval_s = 0.0
    while len(points) >= 5:
        passes += 1
        eval_started_at = perf_counter()
        removable, bridge_errors = _fairing_removable_mask(
            points,
            closed=closed,
            max_local_segment=max_local_segment,
            max_bridge_segment=max_bridge_segment,
            tolerance=tolerance,
            min_improvement_ratio=min_improvement_ratio,
        )
        vector_eval_s += perf_counter() - eval_started_at
        candidate_indices = np.flatnonzero(removable)
        candidates_seen += int(len(candidate_indices))
        if len(candidate_indices) == 0:
            break

        selected_indices = _non_adjacent_indices(candidate_indices, len(points), closed=closed)
        if not selected_indices:
            break
        remove_mask = np.zeros(len(points), dtype=bool)
        remove_mask[np.asarray(selected_indices, dtype=int)] = True
        max_bridge_error = max(max_bridge_error, float(np.max(bridge_errors[remove_mask])))
        points = points[~remove_mask]
        removed += int(np.count_nonzero(remove_mask))

    if removed:
        _logger.info(
            "[PAINT] Source contour fairing removed "
            f"{removed} resampling wiggle sample(s); "
            f"max_bridge_error={max_bridge_error:.4f}mm tolerance={tolerance:.4f}mm"
        )
    if stats is not None:
        stats["passes"] = passes
        stats["candidates"] = candidates_seen
        stats["removed"] = removed
        stats["vector_eval_s"] = vector_eval_s
    return _close_if_needed(points, closed)


def _fairing_removable_mask(
    points: np.ndarray,
    *,
    closed: bool,
    max_local_segment: float,
    max_bridge_segment: float,
    tolerance: float,
    min_improvement_ratio: float,
) -> tuple[np.ndarray, np.ndarray]:
    count = len(points)
    removable = np.zeros(count, dtype=bool)
    bridge_errors = np.zeros(count, dtype=float)
    if count < 5:
        return removable, bridge_errors

    if closed:
        prev_points = np.roll(points, 1, axis=0)
        next_points = np.roll(points, -1, axis=0)
        candidate_mask = np.ones(count, dtype=bool)
    else:
        prev_points = points.copy()
        next_points = points.copy()
        prev_points[1:-1] = points[:-2]
        next_points[1:-1] = points[2:]
        candidate_mask = np.zeros(count, dtype=bool)
        candidate_mask[1:-1] = True

    incoming = points - prev_points
    outgoing = next_points - points
    bridge = next_points - prev_points
    incoming_len = np.linalg.norm(incoming, axis=1)
    outgoing_len = np.linalg.norm(outgoing, axis=1)
    bridge_len = np.linalg.norm(bridge, axis=1)
    path_len = incoming_len + outgoing_len

    valid = (
        candidate_mask
        & (incoming_len > 1e-9)
        & (outgoing_len > 1e-9)
        & (path_len > 1e-9)
        & (incoming_len <= max_local_segment)
        & (outgoing_len <= max_local_segment)
        & (bridge_len > 1e-12)
        & (bridge_len <= max_bridge_segment)
    )
    if not np.any(valid):
        return removable, bridge_errors

    point_from_prev = points - prev_points
    t = np.zeros(count, dtype=float)
    bridge_len_sq = np.einsum("ij,ij->i", bridge, bridge)
    t[valid] = np.einsum("ij,ij->i", point_from_prev, bridge)[valid] / bridge_len_sq[valid]
    t = np.clip(t, 0.0, 1.0)
    projection = prev_points + t[:, None] * bridge
    bridge_errors = np.linalg.norm(points - projection, axis=1)

    local_curvature = np.linalg.norm(next_points - 2.0 * points + prev_points, axis=1)
    bridge_curvature = np.abs(path_len - bridge_len)
    removable = (
        valid
        & (bridge_errors <= tolerance)
        & (bridge_curvature <= local_curvature * (1.0 - min_improvement_ratio))
    )
    return removable, bridge_errors


def _non_adjacent_indices(candidate_indices: np.ndarray, count: int, *, closed: bool) -> list[int]:
    selected: list[int] = []
    blocked = np.zeros(count, dtype=bool)
    for raw_index in candidate_indices:
        index = int(raw_index)
        if blocked[index]:
            continue
        selected.append(index)
        blocked[index] = True
        if index > 0:
            blocked[index - 1] = True
        elif closed:
            blocked[count - 1] = True
        if index + 1 < count:
            blocked[index + 1] = True
        elif closed:
            blocked[0] = True
    if not closed:
        return selected
    if len(selected) > 1 and 0 in selected and count - 1 in selected:
        selected.pop()
    return selected


def _removal_turn_score(points: np.ndarray, remove_index: int, *, closed: bool) -> float:
    count = len(points)
    if count < 4:
        return float("inf")
    if not closed and (remove_index <= 0 or remove_index >= count - 1):
        return float("inf")

    candidate = np.delete(points, remove_index, axis=0)
    if len(candidate) < 3:
        return float("inf")
    mapped_index = remove_index % len(candidate)
    prev_index = (mapped_index - 1) % len(candidate)
    next_index = (mapped_index + 1) % len(candidate)
    if not closed and (prev_index < 0 or next_index >= len(candidate)):
        return float("inf")
    return abs(
        _signed_turn_degrees(
            candidate[prev_index],
            candidate[mapped_index],
            candidate[next_index],
        )
    )





def _close_if_needed(points: np.ndarray, closed: bool) -> np.ndarray:
    if not closed or len(points) == 0:
        return points
    if float(np.linalg.norm(points[0] - points[-1])) <= 1e-9:
        return points
    return np.vstack([points, points[:1]])


def _point_to_segment_distance(point: np.ndarray, start: np.ndarray, end: np.ndarray) -> float:
    segment = np.asarray(end, dtype=float) - np.asarray(start, dtype=float)
    seg_len_sq = float(np.dot(segment, segment))
    if seg_len_sq <= 1e-12:
        return float(np.linalg.norm(np.asarray(point, dtype=float) - np.asarray(start, dtype=float)))
    t = float(np.dot(np.asarray(point, dtype=float) - np.asarray(start, dtype=float), segment) / seg_len_sq)
    t = min(1.0, max(0.0, t))
    projection = np.asarray(start, dtype=float) + t * segment
    return float(np.linalg.norm(np.asarray(point, dtype=float) - projection))




def _merge_unique_xy_points(*point_sets: np.ndarray | None) -> np.ndarray:
    merged: list[np.ndarray] = []
    for point_set in point_sets:
        if point_set is None:
            continue
        try:
            points = np.asarray(point_set, dtype=float).reshape(-1, 2)
        except (TypeError, ValueError):
            continue
        for point in points:
            if not any(float(np.linalg.norm(point - existing)) <= 1e-6 for existing in merged):
                merged.append(point.copy())
    if not merged:
        return np.empty((0, 2), dtype=float)
    return np.asarray(merged, dtype=float)


def _signed_turn_degrees(prev: np.ndarray, current: np.ndarray, nxt: np.ndarray) -> float:
    incoming = np.asarray(current, dtype=float) - np.asarray(prev, dtype=float)
    outgoing = np.asarray(nxt, dtype=float) - np.asarray(current, dtype=float)
    in_len = float(np.linalg.norm(incoming))
    out_len = float(np.linalg.norm(outgoing))
    if in_len <= 1e-9 or out_len <= 1e-9:
        return 0.0
    cross = float(incoming[0] * outgoing[1] - incoming[1] * outgoing[0])
    dot = float(np.dot(incoming, outgoing))
    return float(np.degrees(np.arctan2(cross, dot)))


def _sharp_tangent_boundary_xy(anchor_xy: np.ndarray, threshold_deg: float) -> np.ndarray:
    points = _clean_xy(anchor_xy)
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    closed = len(points) >= 4 and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    turns = np.zeros(len(points), dtype=float)
    turn_range = range(len(points)) if closed else range(1, len(points) - 1)
    for index in turn_range:
        turns[index] = _signed_turn_degrees(
            points[index - 1],
            points[index],
            points[(index + 1) % len(points)],
        )

    threshold = max(float(threshold_deg), 1.0)
    active_threshold = max(5.0, threshold * 0.2)
    candidate_indices = [
        index for index in turn_range
        if abs(float(turns[index])) >= active_threshold
    ]
    if not candidate_indices:
        return np.empty((0, 2), dtype=float)

    clusters: list[list[int]] = []
    current_cluster: list[int] = []
    for index in candidate_indices:
        if current_cluster and index != current_cluster[-1] + 1:
            clusters.append(current_cluster)
            current_cluster = []
        current_cluster.append(index)
    if current_cluster:
        clusters.append(current_cluster)

    if closed and len(clusters) > 1 and clusters[0][0] == 0 and clusters[-1][-1] == len(points) - 1:
        clusters[0] = clusters[-1] + clusters[0]
        clusters.pop()

    sharp_indices: list[int] = []
    abs_turns = np.abs(turns)
    for cluster in clusters:
        total_turn = float(np.sum(abs_turns[cluster]))
        peak_turn = float(np.max(abs_turns[cluster]))
        if total_turn < threshold and peak_turn < threshold:
            continue
        if len(cluster) <= 3 or peak_turn >= threshold:
            sharp_indices.append(cluster[0] % len(points))

    if not sharp_indices:
        return np.empty((0, 2), dtype=float)
    return points[sorted(set(sharp_indices))]
