from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from src.engine.robot.path_preparation.geometry import (
    PATH_TANGENT_HEADING_DEADBAND_DEG,
    PATH_TANGENT_LOOKAHEAD_DISTANCE_MM,
    rebuild_pose_path_from_xy,
)


@dataclass(frozen=True)
class PaintContourInterpolationConfig:
    """Paint-only contour interpolation settings for offline testing."""

    units: str = "mm"
    anchor_spacing_mm: float = 1.0
    execution_spacing_mm: float = 3.0
    straight_cleanup_distance_mm: float = 0.35
    straight_cleanup_turn_deg: float = 3.0
    straight_cleanup_passes: int = 6
    sharp_boundary_deg: float = 45.0
    tangent_lookahead_distance_mm: float = PATH_TANGENT_LOOKAHEAD_DISTANCE_MM
    tangent_heading_deadband_deg: float = PATH_TANGENT_HEADING_DEADBAND_DEG
    rz_mode: str = "path_tangent"


@dataclass(frozen=True)
class PaintContourInterpolationResult:
    """Path representations generated by the paint-only interpolation experiment."""

    units: str
    raw_path: list[list[float]]
    prepared_path: list[list[float]]
    heading_path: list[list[float]]
    execution_path: list[list[float]]
    anchor_xy: list[list[float]]
    cleaned_anchor_xy: list[list[float]] = field(default_factory=list)
    sharp_boundary_xy: list[list[float]] = field(default_factory=list)

    @property
    def raw_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.raw_path, dtype=float)[:, :2])

    @property
    def execution_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.execution_path, dtype=float)[:, :2])


class PaintContourInterpolation:
    """Experimental paint contour interpolation, not wired into production.

    This keeps original contour anchors, adds uniform support points along the
    contour, reconstructs tangent heading once, then produces a final execution
    path that still preserves the anchors and detected sharp boundaries.
    """

    def __init__(self, config: PaintContourInterpolationConfig | None = None) -> None:
        self._config = config or PaintContourInterpolationConfig()

    def build(self, robot_path: list[list[float]]) -> PaintContourInterpolationResult:
        raw_path = [list(point) for point in robot_path]
        if len(raw_path) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path,
                heading_path=raw_path,
                execution_path=raw_path,
                anchor_xy=[list(point[:2]) for point in raw_path],
            )

        raw_xy = _clean_xy(np.asarray(raw_path, dtype=float)[:, :2])
        if len(raw_xy) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path[:1],
                heading_path=raw_path[:1],
                execution_path=raw_path[:1],
                anchor_xy=[list(point[:2]) for point in raw_path[:1]],
            )

        cleaned_anchor_xy = _cleanup_straight_runs(
            raw_xy,
            distance_tolerance_mm=self._config.straight_cleanup_distance_mm,
            turn_tolerance_deg=self._config.straight_cleanup_turn_deg,
            passes=self._config.straight_cleanup_passes,
        )
        prepared_xy = _densify_xy_preserving_anchors(
            cleaned_anchor_xy,
            target_spacing_mm=self._config.anchor_spacing_mm,
        )
        sharp_boundary_xy = _sharp_tangent_boundary_xy(
            cleaned_anchor_xy,
            threshold_deg=self._config.sharp_boundary_deg,
        )
        preserve_xy = _merge_unique_xy_points(cleaned_anchor_xy, sharp_boundary_xy)

        prepared_path = rebuild_pose_path_from_xy(
            prepared_xy,
            raw_path,
            self._config.rz_mode,
            tangent_lookahead_distance_mm=self._config.tangent_lookahead_distance_mm,
            tangent_heading_deadband_deg=self._config.tangent_heading_deadband_deg,
            tangent_boundary_xy=sharp_boundary_xy,
        )
        execution_path = _resample_pose_path_preserving_xy(
            prepared_path,
            target_spacing_mm=self._config.execution_spacing_mm,
            preserve_xy=preserve_xy,
        )

        return PaintContourInterpolationResult(
            units=self._config.units,
            raw_path=raw_path,
            prepared_path=prepared_path,
            heading_path=prepared_path,
            execution_path=execution_path,
            anchor_xy=preserve_xy.tolist(),
            cleaned_anchor_xy=cleaned_anchor_xy.tolist(),
            sharp_boundary_xy=sharp_boundary_xy.tolist(),
        )


def save_paint_contour_interpolation_debug_plot(
    result: PaintContourInterpolationResult,
    output_path: str | Path,
) -> Path:
    """Save a compact before/after plot for the experimental interpolation."""
    import matplotlib.pyplot as plt

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    fig = _build_debug_figure(result)
    fig.savefig(output, dpi=150)
    plt.close(fig)
    return output


def show_paint_contour_interpolation_debug_plot(
    result: PaintContourInterpolationResult,
) -> None:
    """Show a compact before/after plot for the experimental interpolation."""
    import matplotlib.pyplot as plt

    _build_debug_figure(result)
    plt.show()


def _build_debug_figure(result: PaintContourInterpolationResult):
    import matplotlib.pyplot as plt

    raw = np.asarray(result.raw_path, dtype=float)
    prepared = np.asarray(result.prepared_path, dtype=float)
    execution = np.asarray(result.execution_path, dtype=float)
    anchors = np.asarray(result.anchor_xy, dtype=float).reshape(-1, 2) if result.anchor_xy else np.empty((0, 2))
    cleaned = (
        np.asarray(result.cleaned_anchor_xy, dtype=float).reshape(-1, 2)
        if result.cleaned_anchor_xy else np.empty((0, 2))
    )
    boundaries = (
        np.asarray(result.sharp_boundary_xy, dtype=float).reshape(-1, 2)
        if result.sharp_boundary_xy else np.empty((0, 2))
    )

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    raw_rect = compute_min_rect_metrics(raw[:, :2] if len(raw) else np.empty((0, 2)))
    execution_rect = compute_min_rect_metrics(execution[:, :2] if len(execution) else np.empty((0, 2)))
    units = result.units
    fig.suptitle(
        "Paint Contour Interpolation Experiment: "
        f"raw={len(raw)} cleaned={len(cleaned)} prepared={len(prepared)} execution={len(execution)} | "
        f"rect raw={raw_rect['width_mm']:.2f}x{raw_rect['height_mm']:.2f}{units} "
        f"final={execution_rect['width_mm']:.2f}x{execution_rect['height_mm']:.2f}{units} "
        f"delta={execution_rect['width_mm'] - raw_rect['width_mm']:+.2f}x"
        f"{execution_rect['height_mm'] - raw_rect['height_mm']:+.2f}{units}",
        fontsize=12,
    )
    _plot_xy(axes[0], raw, "Raw", units)
    _plot_xy(axes[1], prepared, "Anchor-Preserving Support", units)
    _plot_xy(axes[2], execution, "Final Execution", units)
    _plot_min_rect(axes[0], raw_rect, "raw rect")
    _plot_min_rect(axes[2], execution_rect, "final rect")
    for axis in axes:
        if len(anchors):
            axis.scatter(anchors[:, 0], anchors[:, 1], s=20, c="orange", label="anchors", zorder=4)
        if len(cleaned):
            axis.scatter(cleaned[:, 0], cleaned[:, 1], s=12, c="tab:blue", label="cleaned", zorder=4)
        if len(boundaries):
            axis.scatter(boundaries[:, 0], boundaries[:, 1], s=45, c="cyan", edgecolors="black", label="sharp", zorder=5)
        axis.set_aspect("equal", adjustable="box")
        axis.grid(True, alpha=0.5)
        axis.legend(loc="best")
    fig.tight_layout()
    return fig


def compute_min_rect_metrics(xy_points: np.ndarray) -> dict[str, float]:
    """Return OpenCV min-area rectangle metrics for XY points."""
    import cv2

    points = np.asarray(xy_points, dtype=np.float32)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return {
            "cx_mm": 0.0,
            "cy_mm": 0.0,
            "width_mm": 0.0,
            "height_mm": 0.0,
            "angle_deg": 0.0,
            "area_mm2": 0.0,
        }

    rect = cv2.minAreaRect(points[:, :2].reshape(-1, 1, 2))
    (cx, cy), (width, height), angle = rect
    width = float(width)
    height = float(height)
    angle = float(angle)
    if width < height:
        width, height = height, width
        angle += 90.0
    return {
        "cx_mm": float(cx),
        "cy_mm": float(cy),
        "width_mm": width,
        "height_mm": height,
        "angle_deg": angle,
        "area_mm2": width * height,
    }


def _plot_min_rect(axis, rect: dict[str, float], label: str) -> None:
    import cv2

    if rect["width_mm"] <= 1e-9 or rect["height_mm"] <= 1e-9:
        return
    cv_rect = (
        (float(rect["cx_mm"]), float(rect["cy_mm"])),
        (float(rect["width_mm"]), float(rect["height_mm"])),
        float(rect["angle_deg"]),
    )
    box = cv2.boxPoints(cv_rect)
    box = np.vstack([box, box[:1]])
    axis.plot(box[:, 0], box[:, 1], "--", linewidth=1.5, label=label)


def _plot_xy(axis, path: np.ndarray, title: str, units: str) -> None:
    axis.set_title(f"{title} ({len(path)} pts)")
    if len(path) == 0:
        return
    axis.plot(path[:, 0], path[:, 1], "-o", markersize=2)
    axis.scatter([path[0, 0]], [path[0, 1]], s=45, c="green", label="start", zorder=6)
    axis.scatter([path[-1, 0]], [path[-1, 1]], s=45, c="red", label="end", zorder=6)
    axis.set_xlabel(f"X ({units})")
    axis.set_ylabel(f"Y ({units})")


def _clean_xy(xy_points: np.ndarray) -> np.ndarray:
    points = np.asarray(xy_points, dtype=float)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return np.empty((0, 2), dtype=float)
    points = points[:, :2].copy()
    if len(points) < 2:
        return points
    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    keep_mask = np.concatenate([[True], segment_lengths > 1e-9])
    return points[keep_mask]


def _cleanup_straight_runs(
    xy_points: np.ndarray,
    *,
    distance_tolerance_mm: float,
    turn_tolerance_deg: float,
    passes: int,
) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 4:
        return points

    closed = float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 4:
        return _close_if_needed(points, closed)

    distance_tolerance_mm = max(0.0, float(distance_tolerance_mm))
    turn_tolerance_deg = max(0.0, float(turn_tolerance_deg))
    passes = max(1, int(passes))

    current = points.copy()
    for _ in range(passes):
        if len(current) < 4:
            break
        keep = np.ones(len(current), dtype=bool)
        candidate_range = range(len(current)) if closed else range(1, len(current) - 1)
        removed_any = False
        for index in candidate_range:
            prev_index = (index - 1) % len(current)
            next_index = (index + 1) % len(current)
            prev_point = current[prev_index]
            point = current[index]
            next_point = current[next_index]
            turn = abs(_signed_turn_degrees(prev_point, point, next_point))
            distance = _point_to_segment_distance(point, prev_point, next_point)
            if turn <= turn_tolerance_deg and distance <= distance_tolerance_mm:
                keep[index] = False
                removed_any = True
        if not removed_any:
            break
        current = current[keep]

    return _close_if_needed(current, closed)


def _close_if_needed(points: np.ndarray, closed: bool) -> np.ndarray:
    if not closed or len(points) == 0:
        return points
    if float(np.linalg.norm(points[0] - points[-1])) <= 1e-9:
        return points
    return np.vstack([points, points[:1]])


def _point_to_segment_distance(point: np.ndarray, start: np.ndarray, end: np.ndarray) -> float:
    segment = np.asarray(end, dtype=float) - np.asarray(start, dtype=float)
    seg_len_sq = float(np.dot(segment, segment))
    if seg_len_sq <= 1e-12:
        return float(np.linalg.norm(np.asarray(point, dtype=float) - np.asarray(start, dtype=float)))
    t = float(np.dot(np.asarray(point, dtype=float) - np.asarray(start, dtype=float), segment) / seg_len_sq)
    t = min(1.0, max(0.0, t))
    projection = np.asarray(start, dtype=float) + t * segment
    return float(np.linalg.norm(np.asarray(point, dtype=float) - projection))


def _densify_xy_preserving_anchors(xy_points: np.ndarray, target_spacing_mm: float) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return points

    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return points

    target_spacing_mm = max(0.1, float(target_spacing_mm))
    sample_distances = list(np.arange(0.0, total_length, target_spacing_mm))
    sample_distances.extend(float(distance) for distance in cumulative)
    sample_distances.append(total_length)
    sample_distances = sorted(set(round(float(distance), 9) for distance in sample_distances))
    return np.column_stack(
        [np.interp(sample_distances, cumulative, points[:, dim]) for dim in range(2)]
    )


def _resample_pose_path_preserving_xy(
    path: list[list[float]],
    *,
    target_spacing_mm: float,
    preserve_xy: np.ndarray,
) -> list[list[float]]:
    if len(path) < 2:
        return [list(point) for point in path]

    points = np.asarray(path, dtype=float)
    if points.ndim != 2 or points.shape[0] < 2:
        return [list(point) for point in path]

    segment_lengths = np.linalg.norm(np.diff(points[:, :3], axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return [list(path[0])]

    preserve_distances: list[float] = []
    anchors = np.asarray(preserve_xy, dtype=float).reshape(-1, 2) if len(preserve_xy) else np.empty((0, 2))
    for index, point in enumerate(points):
        if len(anchors) and bool(np.any(np.linalg.norm(anchors - point[:2], axis=1) <= 1e-6)):
            preserve_distances.append(float(cumulative[index]))

    target_spacing_mm = max(1.0, float(target_spacing_mm))
    sample_distances = list(np.arange(0.0, total_length, target_spacing_mm))
    sample_distances.extend(preserve_distances)
    sample_distances.append(total_length)
    sample_distances = sorted(set(round(float(distance), 9) for distance in sample_distances))
    resampled = np.column_stack(
        [np.interp(sample_distances, cumulative, points[:, dim]) for dim in range(points.shape[1])]
    )

    output: list[list[float]] = []
    for point in resampled.tolist():
        if not output or any(abs(float(a) - float(b)) > 1e-9 for a, b in zip(output[-1], point)):
            output.append(point)
    return output


def _merge_unique_xy_points(*point_sets: np.ndarray | None) -> np.ndarray:
    merged: list[np.ndarray] = []
    for point_set in point_sets:
        if point_set is None:
            continue
        try:
            points = np.asarray(point_set, dtype=float).reshape(-1, 2)
        except (TypeError, ValueError):
            continue
        for point in points:
            if not any(float(np.linalg.norm(point - existing)) <= 1e-6 for existing in merged):
                merged.append(point.copy())
    if not merged:
        return np.empty((0, 2), dtype=float)
    return np.asarray(merged, dtype=float)


def _signed_turn_degrees(prev: np.ndarray, current: np.ndarray, nxt: np.ndarray) -> float:
    incoming = np.asarray(current, dtype=float) - np.asarray(prev, dtype=float)
    outgoing = np.asarray(nxt, dtype=float) - np.asarray(current, dtype=float)
    in_len = float(np.linalg.norm(incoming))
    out_len = float(np.linalg.norm(outgoing))
    if in_len <= 1e-9 or out_len <= 1e-9:
        return 0.0
    cross = float(incoming[0] * outgoing[1] - incoming[1] * outgoing[0])
    dot = float(np.dot(incoming, outgoing))
    return float(np.degrees(np.arctan2(cross, dot)))


def _sharp_tangent_boundary_xy(anchor_xy: np.ndarray, threshold_deg: float) -> np.ndarray:
    points = _clean_xy(anchor_xy)
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    closed = len(points) >= 4 and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    turns = np.zeros(len(points), dtype=float)
    turn_range = range(len(points)) if closed else range(1, len(points) - 1)
    for index in turn_range:
        turns[index] = _signed_turn_degrees(
            points[index - 1],
            points[index],
            points[(index + 1) % len(points)],
        )

    threshold = max(float(threshold_deg), 1.0)
    active_threshold = max(5.0, threshold * 0.2)
    candidate_indices = [
        index for index in turn_range
        if abs(float(turns[index])) >= active_threshold
    ]
    if not candidate_indices:
        return np.empty((0, 2), dtype=float)

    clusters: list[list[int]] = []
    current_cluster: list[int] = []
    for index in candidate_indices:
        if current_cluster and index != current_cluster[-1] + 1:
            clusters.append(current_cluster)
            current_cluster = []
        current_cluster.append(index)
    if current_cluster:
        clusters.append(current_cluster)

    if closed and len(clusters) > 1 and clusters[0][0] == 0 and clusters[-1][-1] == len(points) - 1:
        clusters[0] = clusters[-1] + clusters[0]
        clusters.pop()

    sharp_indices: list[int] = []
    abs_turns = np.abs(turns)
    for cluster in clusters:
        total_turn = float(np.sum(abs_turns[cluster]))
        peak_turn = float(np.max(abs_turns[cluster]))
        if total_turn < threshold and peak_turn < threshold:
            continue
        if len(cluster) <= 3 or peak_turn >= threshold:
            sharp_indices.append(cluster[0] % len(points))

    if not sharp_indices:
        return np.empty((0, 2), dtype=float)
    return points[sorted(set(sharp_indices))]
