from __future__ import annotations

import logging
from collections import deque
from dataclasses import dataclass, field
from time import perf_counter

import cv2
import numpy as np
from scipy.optimize import least_squares

from src.engine.robot.path_preparation.geometry import (
    PATH_TANGENT_HEADING_DEADBAND_DEG,
    PATH_TANGENT_LOOKAHEAD_DISTANCE_MM,
    rebuild_pose_path_from_xy,
)
from src.robot_systems.paint.processes.paint.plan.paint_contour_interpolation_debug import (
    save_paint_contour_interpolation_debug_plot,
    show_paint_contour_interpolation_debug_plot,
)

_logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PaintContourInterpolationConfig:
    """Paint contour processing settings.

    The processor is unit-agnostic. In production paint execution it receives
    robot-space millimetres after pixel-to-mm conversion; in standalone vision
    experiments it may receive pixels. No integer rounding is performed here.
    """

    units: str = "mm"
    fit_sample_spacing: float = 1.0
    output_spacing: float = 1.0
    corner_epsilon_ratio: float = 0.004
    bezier_max_error: float = 1.5
    bezier_min_points: int = 10
    bezier_max_depth: int = 10
    sharp_boundary_deg: float = 45.0
    tangent_lookahead_distance_mm: float = PATH_TANGENT_LOOKAHEAD_DISTANCE_MM
    tangent_heading_deadband_deg: float = PATH_TANGENT_HEADING_DEADBAND_DEG
    rz_mode: str = "path_tangent"


@dataclass(frozen=True)
class PaintContourInterpolationResult:
    """Path representations generated by the paint-only interpolation experiment."""

    units: str
    raw_path: list[list[float]]
    prepared_path: list[list[float]]
    heading_path: list[list[float]]
    execution_path: list[list[float]]
    anchor_xy: list[list[float]]
    cleaned_anchor_xy: list[list[float]] = field(default_factory=list)
    sharp_boundary_xy: list[list[float]] = field(default_factory=list)

    @property
    def raw_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.raw_path, dtype=float)[:, :2])

    @property
    def execution_min_rect(self) -> dict[str, float]:
        return compute_min_rect_metrics(np.asarray(self.execution_path, dtype=float)[:, :2])


class PaintContourInterpolation:
    """Curve-preserving paint contour processor.

    The algorithm mirrors the validated standalone runner:
    normalize float XY, sample the closed source contour uniformly, detect hard
    contour corners, fit adaptive cubic Beziers between corners, then sample the
    fitted curve back to a float XY contour. It removes local camera/jitter noise
    while preserving continuous curvature instead of collapsing arcs into chords.
    """

    def __init__(self, config: PaintContourInterpolationConfig | None = None) -> None:
        self._config = config or PaintContourInterpolationConfig()

    def build(self, robot_path: list[list[float]]) -> PaintContourInterpolationResult:
        total_start = perf_counter()
        raw_path = [list(point) for point in robot_path]
        if len(raw_path) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path,
                heading_path=raw_path,
                execution_path=raw_path,
                anchor_xy=[list(point[:2]) for point in raw_path],
            )

        stage_start = perf_counter()
        raw_xy = _clean_xy(np.asarray(raw_path, dtype=float)[:, :2])
        _log_interpolation_timing("clean_xy", stage_start, input_points=len(raw_path), output_points=len(raw_xy))
        if len(raw_xy) < 2:
            return PaintContourInterpolationResult(
                units=self._config.units,
                raw_path=raw_path,
                prepared_path=raw_path[:1],
                heading_path=raw_path[:1],
                execution_path=raw_path[:1],
                anchor_xy=[list(point[:2]) for point in raw_path[:1]],
            )

        stage_start = perf_counter()
        dense_xy = _resample_closed_xy(raw_xy, self._config.fit_sample_spacing)
        _log_interpolation_timing(
            "fit_resample_closed_xy",
            stage_start,
            input_points=len(raw_xy),
            output_points=len(dense_xy),
        )

        stage_start = perf_counter()
        prepared_xy, corner_indices = _smooth_closed_xy_with_beziers(dense_xy, self._config)
        _log_interpolation_timing(
            "smooth_closed_xy_with_beziers",
            stage_start,
            input_points=len(dense_xy),
            output_points=len(prepared_xy),
            corners=len(corner_indices),
        )
        cleaned_anchor_xy = dense_xy

        stage_start = perf_counter()
        sharp_boundary_xy = _sharp_tangent_boundary_xy(
            prepared_xy,
            threshold_deg=self._config.sharp_boundary_deg,
        )
        _log_interpolation_timing(
            "sharp_tangent_boundary_xy",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(sharp_boundary_xy),
        )
        corner_xy = prepared_xy[np.asarray(corner_indices, dtype=int)] if corner_indices else np.empty((0, 2))
        preserve_xy = _merge_unique_xy_points(corner_xy, sharp_boundary_xy)

        stage_start = perf_counter()
        prepared_path = rebuild_pose_path_from_xy(
            prepared_xy,
            raw_path,
            self._config.rz_mode,
            tangent_lookahead_distance_mm=self._config.tangent_lookahead_distance_mm,
            tangent_heading_deadband_deg=self._config.tangent_heading_deadband_deg,
            tangent_boundary_xy=sharp_boundary_xy,
        )
        _log_interpolation_timing(
            "rebuild_prepared_pose_path",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(prepared_path),
        )

        stage_start = perf_counter()
        execution_xy = resample_contour_xy(
            prepared_xy,
            spacing=self._config.output_spacing,
            closed=True,
        )
        _log_interpolation_timing(
            "execution_resample_contour_xy",
            stage_start,
            input_points=len(prepared_xy),
            output_points=len(execution_xy),
        )

        stage_start = perf_counter()
        execution_xy = _fair_resampled_contour_xy(
            execution_xy,
            spacing=self._config.output_spacing,
            closed=True,
        )
        _log_interpolation_timing(
            "fair_resampled_contour_xy",
            stage_start,
            output_points=len(execution_xy),
        )

        stage_start = perf_counter()
        execution_path = rebuild_pose_path_from_xy(
            execution_xy,
            raw_path,
            self._config.rz_mode,
            tangent_lookahead_distance_mm=self._config.tangent_lookahead_distance_mm,
            tangent_heading_deadband_deg=self._config.tangent_heading_deadband_deg,
            tangent_boundary_xy=sharp_boundary_xy,
        )
        _log_interpolation_timing(
            "rebuild_execution_pose_path",
            stage_start,
            input_points=len(execution_xy),
            output_points=len(execution_path),
        )
        _log_interpolation_timing(
            "paint_contour_interpolation_total",
            total_start,
            input_points=len(raw_path),
            output_points=len(execution_path),
        )

        return PaintContourInterpolationResult(
            units=self._config.units,
            raw_path=raw_path,
            prepared_path=prepared_path,
            heading_path=prepared_path,
            execution_path=execution_path,
            anchor_xy=preserve_xy.tolist(),
            cleaned_anchor_xy=cleaned_anchor_xy.tolist(),
            sharp_boundary_xy=sharp_boundary_xy.tolist(),
        )


def _log_interpolation_timing(label: str, started_at: float, **fields: object) -> None:
    suffix = " ".join(f"{key}={value}" for key, value in fields.items())
    if suffix:
        suffix = " " + suffix
    _logger.info("[PATH_PREP_TIMING] stage=%s elapsed_s=%.3f%s", label, perf_counter() - started_at, suffix)


def resample_contour_xy(
    xy_points: np.ndarray,
    *,
    spacing: float,
    closed: bool = True,
) -> np.ndarray:
    """Return a float XY contour/path sampled at approximately *spacing* units.

    This is a linear arclength resampler only. It does not smooth, simplify, or
    fit curves. Use it after pixel-to-mm conversion when the contour shape has
    already been finalized and only execution density is needed.
    """
    source_xy = _remove_degenerate_backtracks(np.asarray(xy_points, dtype=float))
    if closed:
        cleaned = _remove_short_chord_kinks(
            _remove_degenerate_backtracks(_resample_closed_xy(source_xy, spacing)),
            min_chord=max(0.05, float(spacing) * 0.80),
            closed=True,
        )
        if _max_segment_length(cleaned) > float(spacing) * 1.01:
            cleaned = _resample_closed_xy(cleaned, spacing)
        return _close_if_needed(cleaned, True)

    cleaned = _remove_short_chord_kinks(
        _remove_degenerate_backtracks(_resample_open_xy(source_xy, spacing)),
        min_chord=max(0.05, float(spacing) * 0.80),
        closed=False,
    )
    if _max_segment_length(cleaned) > float(spacing) * 1.01:
        cleaned = _resample_open_xy(cleaned, spacing)
    return cleaned


def compute_min_rect_metrics(xy_points: np.ndarray) -> dict[str, float]:
    """Return OpenCV min-area rectangle metrics for XY points."""
    import cv2

    points = np.asarray(xy_points, dtype=np.float32)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return {
            "cx_mm": 0.0,
            "cy_mm": 0.0,
            "width_mm": 0.0,
            "height_mm": 0.0,
            "angle_deg": 0.0,
            "area_mm2": 0.0,
        }

    rect = cv2.minAreaRect(points[:, :2].reshape(-1, 1, 2))
    (cx, cy), (width, height), angle = rect
    width = float(width)
    height = float(height)
    angle = float(angle)
    if width < height:
        width, height = height, width
        angle += 90.0
    return {
        "cx_mm": float(cx),
        "cy_mm": float(cy),
        "width_mm": width,
        "height_mm": height,
        "angle_deg": angle,
        "area_mm2": width * height,
    }


def _resample_closed_xy(xy_points: np.ndarray, spacing: float) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return points

    closed_points = points
    if float(np.linalg.norm(points[0] - points[-1])) > 1e-9:
        closed_points = np.vstack([points, points[:1]])

    segment_lengths = np.linalg.norm(np.diff(closed_points, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    keep = np.r_[True, np.diff(cumulative) > 1e-9]
    closed_points = closed_points[keep]
    cumulative = cumulative[keep]
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return closed_points[:-1]

    spacing = max(0.05, float(spacing))
    sample_distances = np.arange(0.0, total_length, spacing)
    if len(sample_distances) < 3:
        sample_distances = np.linspace(0.0, total_length, 3, endpoint=False)
    return np.column_stack(
        [np.interp(sample_distances, cumulative, closed_points[:, dim]) for dim in range(2)]
    ).astype(np.float64)


def _resample_open_xy(xy_points: np.ndarray, spacing: float) -> np.ndarray:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return points

    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    keep = np.r_[True, np.diff(cumulative) > 1e-9]
    points = points[keep]
    cumulative = cumulative[keep]
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return points

    spacing = max(0.05, float(spacing))
    sample_distances = list(np.arange(0.0, total_length, spacing))
    if not sample_distances or abs(sample_distances[-1] - total_length) > 1e-9:
        sample_distances.append(total_length)
    return np.column_stack(
        [np.interp(sample_distances, cumulative, points[:, dim]) for dim in range(2)]
    ).astype(np.float64)


def _max_segment_length(xy_points: np.ndarray) -> float:
    points = _clean_xy(xy_points)
    if len(points) < 2:
        return 0.0
    return float(np.max(np.linalg.norm(np.diff(points, axis=0), axis=1)))


def _smooth_closed_xy_with_beziers(
    dense_xy: np.ndarray,
    config: PaintContourInterpolationConfig,
) -> tuple[np.ndarray, list[int]]:
    dense = _clean_xy(dense_xy)
    if len(dense) < 3:
        return dense.astype(np.float64), []

    corner_indices = _find_corner_indices(dense, config.corner_epsilon_ratio)
    if len(corner_indices) < 3:
        return dense.astype(np.float64), []

    segments = _split_closed_points(dense, corner_indices)
    all_points: list[np.ndarray] = []
    for segment in segments:
        beziers = _adaptive_bezier_fit(segment, config, depth=0)
        for control_points in beziers:
            sampled = _sample_bezier_segment(control_points, config.output_spacing)
            if len(sampled):
                all_points.append(sampled[:-1] if len(sampled) > 1 else sampled)

    if not all_points:
        return dense.astype(np.float64), corner_indices
    result = _rotate_xy_to_nearest_start(_clean_xy(np.vstack(all_points)), dense[0])
    remapped_corner_indices = _nearest_indices(result, dense[np.asarray(corner_indices, dtype=int)])
    return result.astype(np.float64), remapped_corner_indices


def _rotate_xy_to_nearest_start(points: np.ndarray, start_xy: np.ndarray) -> np.ndarray:
    path = _clean_xy(points)
    if len(path) < 2:
        return path
    start = np.asarray(start_xy, dtype=np.float64).reshape(2)
    index = int(np.argmin(np.linalg.norm(path - start, axis=1)))
    if index <= 0:
        return path
    return np.vstack([path[index:], path[:index]])


def _nearest_indices(points: np.ndarray, query_points: np.ndarray) -> list[int]:
    path = _clean_xy(points)
    queries = _clean_xy(query_points)
    if len(path) == 0 or len(queries) == 0:
        return []
    indices = [int(np.argmin(np.linalg.norm(path - query, axis=1))) for query in queries]
    return sorted(set(indices))


def _find_corner_indices(dense_xy: np.ndarray, epsilon_ratio: float) -> list[int]:
    points = _clean_xy(dense_xy)
    if len(points) < 3:
        return []
    contour = np.ascontiguousarray(points.astype(np.float32).reshape(-1, 1, 2))
    epsilon = max(1e-6, float(epsilon_ratio)) * float(cv2.arcLength(contour, True))
    approx = cv2.approxPolyDP(contour, epsilon, True)
    corners = np.asarray(approx, dtype=np.float64).reshape(-1, 2)
    indices: list[int] = []
    for corner in corners:
        index = int(np.argmin(np.linalg.norm(points - corner, axis=1)))
        indices.append(index)
    return sorted(set(indices))


def _split_closed_points(points: np.ndarray, corner_indices: list[int]) -> list[np.ndarray]:
    dense = _clean_xy(points)
    count = len(dense)
    if count < 4:
        return []
    corners = sorted(set(int(index) % count for index in corner_indices))
    segments: list[np.ndarray] = []
    for start, end in zip(corners, corners[1:] + [corners[0] + count]):
        if end >= count:
            segment = np.vstack([dense[start:], dense[: end - count + 1]])
        else:
            segment = dense[start: end + 1]
        if len(segment) >= 4:
            segments.append(segment)
    return segments


def _bezier(t: np.ndarray, p0: np.ndarray, p1: np.ndarray, p2: np.ndarray, p3: np.ndarray) -> np.ndarray:
    parameter = np.asarray(t, dtype=np.float64)[:, None]
    return (
        (1.0 - parameter) ** 3 * p0
        + 3.0 * (1.0 - parameter) ** 2 * parameter * p1
        + 3.0 * (1.0 - parameter) * parameter ** 2 * p2
        + parameter ** 3 * p3
    )


def _fit_cubic_bezier(points: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
    samples = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    p0 = samples[0]
    p3 = samples[-1]
    chord = p3 - p0
    p1_initial = p0 + chord / 3.0
    p2_initial = p0 + 2.0 * chord / 3.0

    segment_lengths = np.linalg.norm(np.diff(samples, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(segment_lengths)])
    total_length = float(cumulative[-1])
    if total_length <= 1e-9:
        return p0, p1_initial, p2_initial, p3, 0.0

    parameters = cumulative / total_length

    def residual(values: np.ndarray) -> np.ndarray:
        p1 = values[:2]
        p2 = values[2:]
        return (_bezier(parameters, p0, p1, p2, p3) - samples).ravel()

    result = least_squares(
        residual,
        np.hstack([p1_initial, p2_initial]),
        max_nfev=80,
    )
    p1 = result.x[:2]
    p2 = result.x[2:]
    fitted = _bezier(parameters, p0, p1, p2, p3)
    error = float(np.max(np.linalg.norm(fitted - samples, axis=1)))
    return p0, p1, p2, p3, error


def _adaptive_bezier_fit(
    points: np.ndarray,
    config: PaintContourInterpolationConfig,
    *,
    depth: int,
) -> list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
    min_points = max(4, int(config.bezier_min_points))
    max_depth = max(1, int(config.bezier_max_depth))
    if len(points) < min_points or depth >= max_depth:
        p0, p1, p2, p3, _ = _fit_cubic_bezier(points)
        return [(p0, p1, p2, p3)]

    p0, p1, p2, p3, error = _fit_cubic_bezier(points)
    if error <= max(0.01, float(config.bezier_max_error)):
        return [(p0, p1, p2, p3)]

    midpoint = len(points) // 2
    return (
        _adaptive_bezier_fit(points[: midpoint + 1], config, depth=depth + 1)
        + _adaptive_bezier_fit(points[midpoint:], config, depth=depth + 1)
    )


def _sample_bezier_segment(
    control_points: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray],
    spacing: float,
) -> np.ndarray:
    p0, p1, p2, p3 = control_points
    approx_length = (
        float(np.linalg.norm(p1 - p0))
        + float(np.linalg.norm(p2 - p1))
        + float(np.linalg.norm(p3 - p2))
    )
    spacing = max(0.05, float(spacing))
    count = max(8, int(np.ceil(approx_length / spacing)) + 1)
    return _bezier(np.linspace(0.0, 1.0, count), p0, p1, p2, p3)


def _clean_xy(xy_points: np.ndarray) -> np.ndarray:
    points = np.asarray(xy_points, dtype=float)
    if points.ndim != 2 or points.shape[0] == 0 or points.shape[1] < 2:
        return np.empty((0, 2), dtype=float)
    points = points[:, :2].copy()
    if len(points) < 2:
        return points
    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
    keep_mask = np.concatenate([[True], segment_lengths > 1e-9])
    return points[keep_mask]


def _remove_degenerate_backtracks(xy_points: np.ndarray) -> np.ndarray:
    """Remove tiny reversed samples that create a local 180-degree fold."""
    points = _clean_xy(xy_points)
    if len(points) < 4:
        return points

    closed = float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 4:
        return _close_if_needed(points, closed)

    changed = True
    while changed and len(points) >= 4:
        changed = False
        keep = np.ones(len(points), dtype=bool)
        for index in range(len(points)):
            prev_index = (index - 1) % len(points) if closed else index - 1
            next_index = (index + 1) % len(points) if closed else index + 1
            if prev_index < 0 or next_index >= len(points):
                continue

            incoming = points[index] - points[prev_index]
            outgoing = points[next_index] - points[index]
            incoming_len = float(np.linalg.norm(incoming))
            outgoing_len = float(np.linalg.norm(outgoing))
            if incoming_len <= 1e-9 or outgoing_len <= 1e-9:
                continue
            if incoming_len > min(0.75, outgoing_len * 0.75):
                continue

            turn_cos = float(np.dot(incoming, outgoing) / (incoming_len * outgoing_len))
            if turn_cos > -0.95:
                continue

            bridge = points[next_index] - points[prev_index]
            bridge_len = float(np.linalg.norm(bridge))
            if bridge_len <= 1e-9:
                continue
            bridge_cos = float(np.dot(bridge, outgoing) / (bridge_len * outgoing_len))
            if bridge_cos < 0.95:
                continue

            keep[index] = False
            changed = True

        if changed:
            points = points[keep]

    return _close_if_needed(points, closed)


def _remove_short_chord_kinks(
    xy_points: np.ndarray,
    *,
    min_chord: float,
    closed: bool,
) -> np.ndarray:
    """Remove sub-spacing kink samples introduced by contour smoothing/resampling.

    The pivot projector treats every final contour segment as physical contact
    travel. A tiny chord with a large heading change becomes many near-pure
    rotation samples and can create a local cusp in the robot command path.
    """
    points = _clean_xy(xy_points)
    if len(points) < 4:
        return points

    if closed and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6:
        points = points[:-1]
    if len(points) < 4:
        return _close_if_needed(points, closed)

    min_chord = max(0.0, float(min_chord))
    changed = True
    while changed and len(points) >= 4:
        changed = False
        segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)
        if closed:
            segment_lengths = np.append(
                segment_lengths,
                float(np.linalg.norm(points[0] - points[-1])),
            )

        candidate_indices = range(len(segment_lengths)) if closed else range(len(segment_lengths))
        for segment_index in candidate_indices:
            if segment_lengths[segment_index] >= min_chord:
                continue
            left_index = segment_index
            right_index = (segment_index + 1) % len(points)
            if not closed and (left_index == 0 or right_index == len(points) - 1):
                continue

            remove_left_score = _removal_turn_score(points, left_index, closed=closed)
            remove_right_score = _removal_turn_score(points, right_index, closed=closed)
            remove_index = left_index if remove_left_score <= remove_right_score else right_index
            if not closed and (remove_index <= 0 or remove_index >= len(points) - 1):
                continue
            points = np.delete(points, remove_index, axis=0)
            changed = True
            break

    return _close_if_needed(points, closed)


def _fair_resampled_contour_xy(
    xy_points: np.ndarray,
    *,
    spacing: float,
    closed: bool,
) -> np.ndarray:
    """Remove tiny local resampling wiggles before pivot projection.

    Projection treats the source contour as physical contact geometry, so this
    pass is intentionally conservative: it only removes a point when the direct
    bridge stays within the paint-scale tolerance and clearly lowers local
    second-difference curvature.
    """
    points = _clean_xy(xy_points)
    if len(points) < 5:
        return points

    if closed and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6:
        points = points[:-1]
    if len(points) < 5:
        return _close_if_needed(points, closed)

    spacing = max(0.05, float(spacing))
    tolerance = max(0.03, min(0.10, spacing * 0.10))
    max_local_segment = spacing * 2.5
    min_improvement_ratio = 0.35

    count = len(points)
    active = np.ones(count, dtype=bool)
    prev_indices = np.arange(count, dtype=int) - 1
    next_indices = np.arange(count, dtype=int) + 1
    if closed:
        prev_indices[0] = count - 1
        next_indices[-1] = 0
        candidates = deque(range(count))
    else:
        candidates = deque(range(1, count - 1))

    active_count = count
    removed = 0
    max_bridge_error = 0.0
    while candidates and active_count >= 5:
        index = candidates.popleft()
        if not active[index]:
            continue
        if not closed and (prev_indices[index] < 0 or next_indices[index] >= count):
            continue

        prev_index = prev_indices[index]
        next_index = next_indices[index]
        if not active[prev_index] or not active[next_index]:
            continue

        bridge_error = _fairing_bridge_error_if_removable(
            points,
            prev_index,
            index,
            next_index,
            max_local_segment=max_local_segment,
            tolerance=tolerance,
            min_improvement_ratio=min_improvement_ratio,
        )
        if bridge_error is None:
            continue

        active[index] = False
        next_indices[prev_index] = next_index
        prev_indices[next_index] = prev_index
        active_count -= 1
        removed += 1
        max_bridge_error = max(max_bridge_error, bridge_error)

        for candidate in (prev_indices[prev_index], prev_index, next_index, next_indices[next_index]):
            if active[candidate] and (closed or 0 < candidate < count - 1):
                candidates.append(candidate)

    if removed:
        _logger.info(
            "[PAINT] Source contour fairing removed "
            f"{removed} resampling wiggle sample(s); "
            f"max_bridge_error={max_bridge_error:.4f}mm tolerance={tolerance:.4f}mm"
        )
    return _close_if_needed(_active_points_in_order(points, active, next_indices, closed), closed)


def _fairing_bridge_error_if_removable(
    points: np.ndarray,
    prev_index: int,
    index: int,
    next_index: int,
    *,
    max_local_segment: float,
    tolerance: float,
    min_improvement_ratio: float,
) -> float | None:
    prev_point = points[prev_index]
    point = points[index]
    next_point = points[next_index]
    incoming_len = float(np.linalg.norm(point - prev_point))
    outgoing_len = float(np.linalg.norm(next_point - point))
    if incoming_len <= 1e-9 or outgoing_len <= 1e-9:
        return None
    if incoming_len > max_local_segment or outgoing_len > max_local_segment:
        return None

    bridge_error = _point_to_segment_distance(point, prev_point, next_point)
    if bridge_error > tolerance:
        return None

    local_curvature = float(np.linalg.norm(next_point - 2.0 * point + prev_point))
    bridge_len = float(np.linalg.norm(next_point - prev_point))
    path_len = incoming_len + outgoing_len
    if path_len <= 1e-9:
        return None
    bridge_curvature = abs(path_len - bridge_len)
    if bridge_curvature > local_curvature * (1.0 - min_improvement_ratio):
        return None
    return bridge_error


def _active_points_in_order(
    points: np.ndarray,
    active: np.ndarray,
    next_indices: np.ndarray,
    closed: bool,
) -> np.ndarray:
    active_indices = np.flatnonzero(active)
    if len(active_indices) == 0:
        return np.empty((0, 2), dtype=float)
    if not closed:
        return points[active]

    ordered = []
    start = int(active_indices[0])
    index = start
    for _ in range(len(active_indices)):
        ordered.append(points[index])
        index = int(next_indices[index])
        if index == start:
            break
    return np.asarray(ordered, dtype=float)


def _removal_turn_score(points: np.ndarray, remove_index: int, *, closed: bool) -> float:
    count = len(points)
    if count < 4:
        return float("inf")
    if not closed and (remove_index <= 0 or remove_index >= count - 1):
        return float("inf")

    candidate = np.delete(points, remove_index, axis=0)
    if len(candidate) < 3:
        return float("inf")
    mapped_index = remove_index % len(candidate)
    prev_index = (mapped_index - 1) % len(candidate)
    next_index = (mapped_index + 1) % len(candidate)
    if not closed and (prev_index < 0 or next_index >= len(candidate)):
        return float("inf")
    return abs(
        _signed_turn_degrees(
            candidate[prev_index],
            candidate[mapped_index],
            candidate[next_index],
        )
    )





def _close_if_needed(points: np.ndarray, closed: bool) -> np.ndarray:
    if not closed or len(points) == 0:
        return points
    if float(np.linalg.norm(points[0] - points[-1])) <= 1e-9:
        return points
    return np.vstack([points, points[:1]])


def _point_to_segment_distance(point: np.ndarray, start: np.ndarray, end: np.ndarray) -> float:
    segment = np.asarray(end, dtype=float) - np.asarray(start, dtype=float)
    seg_len_sq = float(np.dot(segment, segment))
    if seg_len_sq <= 1e-12:
        return float(np.linalg.norm(np.asarray(point, dtype=float) - np.asarray(start, dtype=float)))
    t = float(np.dot(np.asarray(point, dtype=float) - np.asarray(start, dtype=float), segment) / seg_len_sq)
    t = min(1.0, max(0.0, t))
    projection = np.asarray(start, dtype=float) + t * segment
    return float(np.linalg.norm(np.asarray(point, dtype=float) - projection))




def _merge_unique_xy_points(*point_sets: np.ndarray | None) -> np.ndarray:
    merged: list[np.ndarray] = []
    for point_set in point_sets:
        if point_set is None:
            continue
        try:
            points = np.asarray(point_set, dtype=float).reshape(-1, 2)
        except (TypeError, ValueError):
            continue
        for point in points:
            if not any(float(np.linalg.norm(point - existing)) <= 1e-6 for existing in merged):
                merged.append(point.copy())
    if not merged:
        return np.empty((0, 2), dtype=float)
    return np.asarray(merged, dtype=float)


def _signed_turn_degrees(prev: np.ndarray, current: np.ndarray, nxt: np.ndarray) -> float:
    incoming = np.asarray(current, dtype=float) - np.asarray(prev, dtype=float)
    outgoing = np.asarray(nxt, dtype=float) - np.asarray(current, dtype=float)
    in_len = float(np.linalg.norm(incoming))
    out_len = float(np.linalg.norm(outgoing))
    if in_len <= 1e-9 or out_len <= 1e-9:
        return 0.0
    cross = float(incoming[0] * outgoing[1] - incoming[1] * outgoing[0])
    dot = float(np.dot(incoming, outgoing))
    return float(np.degrees(np.arctan2(cross, dot)))


def _sharp_tangent_boundary_xy(anchor_xy: np.ndarray, threshold_deg: float) -> np.ndarray:
    points = _clean_xy(anchor_xy)
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    closed = len(points) >= 4 and float(np.linalg.norm(points[0] - points[-1])) <= 1e-6
    if closed:
        points = points[:-1]
    if len(points) < 3:
        return np.empty((0, 2), dtype=float)

    turns = np.zeros(len(points), dtype=float)
    turn_range = range(len(points)) if closed else range(1, len(points) - 1)
    for index in turn_range:
        turns[index] = _signed_turn_degrees(
            points[index - 1],
            points[index],
            points[(index + 1) % len(points)],
        )

    threshold = max(float(threshold_deg), 1.0)
    active_threshold = max(5.0, threshold * 0.2)
    candidate_indices = [
        index for index in turn_range
        if abs(float(turns[index])) >= active_threshold
    ]
    if not candidate_indices:
        return np.empty((0, 2), dtype=float)

    clusters: list[list[int]] = []
    current_cluster: list[int] = []
    for index in candidate_indices:
        if current_cluster and index != current_cluster[-1] + 1:
            clusters.append(current_cluster)
            current_cluster = []
        current_cluster.append(index)
    if current_cluster:
        clusters.append(current_cluster)

    if closed and len(clusters) > 1 and clusters[0][0] == 0 and clusters[-1][-1] == len(points) - 1:
        clusters[0] = clusters[-1] + clusters[0]
        clusters.pop()

    sharp_indices: list[int] = []
    abs_turns = np.abs(turns)
    for cluster in clusters:
        total_turn = float(np.sum(abs_turns[cluster]))
        peak_turn = float(np.max(abs_turns[cluster]))
        if total_turn < threshold and peak_turn < threshold:
            continue
        if len(cluster) <= 3 or peak_turn >= threshold:
            sharp_indices.append(cluster[0] % len(points))

    if not sharp_indices:
        return np.empty((0, 2), dtype=float)
    return points[sorted(set(sharp_indices))]
