_EXECUTION_INTERPOLATION_SPACING_MM = 10.0
_EXECUTION_MIN_PREPROCESS_SPACING_MM = 2.5
_EXECUTION_DENSE_SAMPLING_FACTOR = 0.25
_EXECUTION_OUTPUT_SPACING_SCALE = 0.75
_EXECUTION_MIN_OUTPUT_SPACING_MM = 6.0
_HEADING_SUPPORT_SPACING_MM = 1.0
_SHARP_TANGENT_BOUNDARY_DEG = 45.0
_EXECUTION_DEFAULT_OUTPUT_SPACING_MM = max(
    _EXECUTION_MIN_OUTPUT_SPACING_MM,
    _EXECUTION_INTERPOLATION_SPACING_MM * _EXECUTION_OUTPUT_SPACING_SCALE,
)
_AUTO_DENSIFY_TRIGGER_RATIO = 2.5
_AUTO_DENSIFY_TARGET_RATIO = 1.25
_DEFAULT_WORKPIECE_HEIGHT_MM = 0.0
_SEGMENT_PREPROCESS_MIN_SPACING_KEY = "preprocess_min_spacing_mm"
_SEGMENT_INTERPOLATION_SPACING_KEY = "interpolation_spacing_mm"
_SEGMENT_DENSE_SAMPLING_FACTOR_KEY = "dense_sampling_factor"
_SEGMENT_EXECUTION_SPACING_KEY = "execution_spacing_mm"
_SEGMENT_TANGENT_LOOKAHEAD_DISTANCE_KEY = "path_tangent_lookahead_mm"
_SEGMENT_TANGENT_DEADBAND_KEY = "path_tangent_deadband_deg"
_CANONICALIZE_WORKPIECE_LAYER_CONTOUR = True
_TEMPORARILY_SKIP_CONTOUR_INTERPOLATION = False
PIXEL_TO_MM_MODE_GEOMETRY_PPM_ANCHOR = "geometry_ppm_anchor"
PIXEL_TO_MM_MODE_HOMOGRAPHY_RESIDUAL = "homography_residual"
_PIXEL_TO_MM_MODES = {
    PIXEL_TO_MM_MODE_GEOMETRY_PPM_ANCHOR,
    PIXEL_TO_MM_MODE_HOMOGRAPHY_RESIDUAL,
}
